server:
  port: 8765

spring:
  application:
    name: sc-service-feign

# 配置spring cloud 服务发现
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
